### ISSUE TITLE
Static extractor broken (at least from YAML)

### ISSUE THREAD

**Issue by VorpalBlade** [html2rss/html2rss#157]
Use the following example yml file:

```yaml
channel:
  url: https://google.com
selectors:
  items:
    selector: html
  title:
    extractor: static
    static: "Test string"
  description:
    selector: body
```

The syntax matches what is documented in the comment of https://github.com/html2rss/html2rss/blob/master/lib/html2rss/item_extractors/static.rb

Running this through html2rss results in the following:
```
bundler: failed to load command: html2rss (/home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/html2rss)
/home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/config/selectors.rb:36:in `initialize': unknown keywords: static (ArgumentError)
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/config/selectors.rb:36:in `new'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/config/selectors.rb:36:in `selector'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/config.rb:55:in `selector_attributes_with_channel'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:55:in `extract'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:46:in `method_missing'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:74:in `title_or_description'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:67:in `valid?'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:126:in `keep_if'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/item.rb:126:in `from_url'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/rss_builder.rb:26:in `block in build'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/rss_builder.rb:20:in `build'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss.rb:65:in `feed'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss.rb:38:in `feed_from_yaml_config'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/lib/html2rss/cli.rb:26:in `feed'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/html2rss-f4feed552def/exe/html2rss:6:in `<top (required)>'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/html2rss:25:in `load'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/html2rss:25:in `<top (required)>'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:58:in `load'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:23:in `run'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli.rb:484:in `exec'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli.rb:31:in `dispatch'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/cli.rb:25:in `start'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/exe/bundle:48:in `block in <top (required)>'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/arvid/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/exe/bundle:36:in `<top (required)>'
	from /home/arvid/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /home/arvid/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

rss2html was installed as per the instructions in https://github.com/html2rss/html2rss-configs 

I'm a python & C++ programmer normally, not a ruby dev, so I may be doing something wrong.

**Comment by gildesmarais** [comment]
Hey there, thanks for the report. There has been a bug and it's fixed. Please do a `bundle update html2rss` and try again. :)
