### ISSUE TITLE
Unable to parse a url via link selector

### ISSUE THREAD

**Issue by Lcchy** [html2rss/html2rss#169]
Hi there, first of all thanks a lot for the great project, it is exactly what I've been looking for.

I am trying to generate a feed but am unable to correctly parse the link. As I've never used Ruby I am unsure if this comes from my config or is a bug. 
The selected link is relative and html2rss should normally prepend the base I think.
Here's the config:

```
will:
  channel:
    url: https://dumpoir.com/v/will_bosi
    title: Will Bosi
    ttl: 120
  selectors:
    items:
      selector: .content__item
    title:
      selector: .content__text
    link:
      selector: .content__item > .content__img-wrap > a
      extractor: href
```

And here the error I am getting
```
/usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/utils.rb:21:in `build_absolute_url_from_relative': undefined method `absolute?' for nil (NoMethodError)

      return url if url.absolute?
                       ^^^^^^^^^^
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/item_extractors/href.rb:39:in `get'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/item.rb:58:in `extract'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/item.rb:46:in `method_missing'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder/item.rb:22:in `public_send'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder/item.rb:22:in `block in add'
	from /usr/local/lib/ruby/3.3.0/set.rb:501:in `each_key'
	from /usr/local/lib/ruby/3.3.0/set.rb:501:in `each'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder/item.rb:21:in `add'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder.rb:29:in `block (2 levels) in build'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder.rb:28:in `each'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder.rb:28:in `block in build'
	from /usr/local/lib/ruby/gems/3.3.0/gems/rss-0.3.0/lib/rss/maker/base.rb:439:in `make'
	from /usr/local/lib/ruby/gems/3.3.0/gems/rss-0.3.0/lib/rss/maker/base.rb:403:in `make'
	from /usr/local/lib/ruby/gems/3.3.0/gems/rss-0.3.0/lib/rss/maker.rb:29:in `make'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/rss_builder.rb:20:in `build'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss.rb:65:in `feed'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss.rb:38:in `feed_from_yaml_config'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/lib/html2rss/cli.rb:26:in `feed'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/bundler/gems/html2rss-8e9c589fbd73/exe/html2rss:6:in `<top (required)>'
	from /app/bin/html2rss:27:in `load'
	from /app/bin/html2rss:27:in `<main>'
```

Any help or pointers would be very welcome! Thanks!

EDIT:
FYI the url to extract looks like this:  `<a href="/c/2319792744204593923" style="display: block; position: relative;">`
Maybe the leading `/` confuses the parser into thinking its an absolute path?

**Comment by Lcchy** [comment]
I have been able to use the link selector correctly with similar links on another website.
I think that the issue is probably on my side so I will close the issue.
